/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface SmLoading {
    }
    interface SmSideDrawer {
        "drawerTitle": string;
        "open": () => Promise<void>;
        "opened": boolean;
    }
    interface SmStockFinder {
        "stockSymbol": string;
    }
    interface SmStockPrice {
        "stockSymbol": string;
    }
    interface SmToolTip {
        "toolTipInfo": string;
        "toolTipText": string;
    }
}
declare global {
    interface HTMLSmLoadingElement extends Components.SmLoading, HTMLStencilElement {
    }
    var HTMLSmLoadingElement: {
        prototype: HTMLSmLoadingElement;
        new (): HTMLSmLoadingElement;
    };
    interface HTMLSmSideDrawerElement extends Components.SmSideDrawer, HTMLStencilElement {
    }
    var HTMLSmSideDrawerElement: {
        prototype: HTMLSmSideDrawerElement;
        new (): HTMLSmSideDrawerElement;
    };
    interface HTMLSmStockFinderElement extends Components.SmStockFinder, HTMLStencilElement {
    }
    var HTMLSmStockFinderElement: {
        prototype: HTMLSmStockFinderElement;
        new (): HTMLSmStockFinderElement;
    };
    interface HTMLSmStockPriceElement extends Components.SmStockPrice, HTMLStencilElement {
    }
    var HTMLSmStockPriceElement: {
        prototype: HTMLSmStockPriceElement;
        new (): HTMLSmStockPriceElement;
    };
    interface HTMLSmToolTipElement extends Components.SmToolTip, HTMLStencilElement {
    }
    var HTMLSmToolTipElement: {
        prototype: HTMLSmToolTipElement;
        new (): HTMLSmToolTipElement;
    };
    interface HTMLElementTagNameMap {
        "sm-loading": HTMLSmLoadingElement;
        "sm-side-drawer": HTMLSmSideDrawerElement;
        "sm-stock-finder": HTMLSmStockFinderElement;
        "sm-stock-price": HTMLSmStockPriceElement;
        "sm-tool-tip": HTMLSmToolTipElement;
    }
}
declare namespace LocalJSX {
    interface SmLoading {
    }
    interface SmSideDrawer {
        "drawerTitle"?: string;
        "opened"?: boolean;
    }
    interface SmStockFinder {
        "onSmSymbolSelected"?: (event: CustomEvent<string>) => void;
        "stockSymbol"?: string;
    }
    interface SmStockPrice {
        "stockSymbol"?: string;
    }
    interface SmToolTip {
        "toolTipInfo"?: string;
        "toolTipText"?: string;
    }
    interface IntrinsicElements {
        "sm-loading": SmLoading;
        "sm-side-drawer": SmSideDrawer;
        "sm-stock-finder": SmStockFinder;
        "sm-stock-price": SmStockPrice;
        "sm-tool-tip": SmToolTip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sm-loading": LocalJSX.SmLoading & JSXBase.HTMLAttributes<HTMLSmLoadingElement>;
            "sm-side-drawer": LocalJSX.SmSideDrawer & JSXBase.HTMLAttributes<HTMLSmSideDrawerElement>;
            "sm-stock-finder": LocalJSX.SmStockFinder & JSXBase.HTMLAttributes<HTMLSmStockFinderElement>;
            "sm-stock-price": LocalJSX.SmStockPrice & JSXBase.HTMLAttributes<HTMLSmStockPriceElement>;
            "sm-tool-tip": LocalJSX.SmToolTip & JSXBase.HTMLAttributes<HTMLSmToolTipElement>;
        }
    }
}
